### ISSUE TITLE
Je kuny niet van Rapid maar Intern

### ISSUE THREAD

**Issue by queribox** [PJvanDiepen/COOLbackend#25]
Eenmaal in het menu gekozen voor Rapid, kun je niet Interne meer selecteren
![0-0-0_1](https://github.com/PJvanDiepen/COOLbackend/assets/129966758/6ce1c5ee-5434-40cb-9c62-5f8fb7f0b715)

**Comment by PJvanDiepen** [comment]
Dit wordt opgelost in 0-0-0.nl versie 0.8.25
